# Generated by Django 4.0.1 on 2022-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Phoneno', models.CharField(max_length=12)),
                ('City', models.CharField(max_length=122)),
                ('Address', models.CharField(max_length=122)),
                ('Zip', models.CharField(max_length=122)),
                ('ch', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
