# Generated by Django 4.0.1 on 2022-01-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_ch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Zip',
            field=models.CharField(max_length=12),
        ),
    ]
