# Generated by Django 4.0.1 on 2022-02-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Phoneno',
            new_name='PhoneNo',
        ),
    ]
